### ISSUE TITLE
闰年增加的问题

### ISSUE THREAD

**Issue by jackylany** [Andrew-M-C/go.timeconv#1]
var startAt int64 = 1677513600 // 2023-02-28  
t := time.Unix(startAt, 0) 

ntMonth := timeconv.AddDate(t, 0, 12, 0)  
ntYear := timeconv.AddDate(t, 1, 0, 0)  

fmt.Println(ntMonth.Format("2006-01-02"))  
fmt.Println(ntYear.Format("2006-01-02"))

// 打印结果  
// 2024-02-28  
// 2024-02-28

**Comment by jackylany** [comment]
我认为的效果是增加自然月，2023-02-28 增加一年就是 2024-02-29

**Comment by Andrew-M-C** [comment]
哎呀非常抱歉现在才看到。2023-02-28 增加一年到底是不是 2-29，这个是存在争议的，因此我没有实现这个 feature，这是特意考虑的。

这个问题其实也可以类比为 2023-04-30 增加一个月，到底应该是 05-30 还是 05-31，我选择的是前者，因为这是无歧义的

如果你确实需要实现类似的功能（每个月最后一天），可以用 2023-01-31 为基准去增加

**Comment by jackylany** [comment]
> 哎呀非常抱歉现在才看到。2023-02-28 增加一年到底是不是 2-29，这个是存在争议的，因此我没有实现这个 feature，这是特意考虑的。
> 
> 这个问题其实也可以类比为 2023-04-30 增加一个月，到底应该是 05-30 还是 05-31，我选择的是前者，因为这是无歧义的
> 
> 如果你确实需要实现类似的功能（每个月最后一天），可以用 2023-01-31 为基准去增加

好的，十分感谢解答
